-- MySQL Script generated by MySQL Workbench
-- Thu Apr 19 16:29:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bapersdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bapersdb` ;

-- -----------------------------------------------------
-- Schema bapersdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bapersdb` DEFAULT CHARACTER SET utf8 ;
USE `bapersdb` ;

-- -----------------------------------------------------
-- Table `bapersdb`.`account_holer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`account_holer` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`account_holer` (
  `idaccount_holer` INT NOT NULL AUTO_INCREMENT,
  `holder_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idaccount_holer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bapersdb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`customer` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`customer` (
  `customer_id` VARCHAR(15) NOT NULL,
  `first_name` VARCHAR(25) NOT NULL,
  `second_name` VARCHAR(25) NOT NULL,
  `state` VARCHAR(15) NULL,
  `phone` VARCHAR(15) NOT NULL,
  `address_Line2` VARCHAR(20) CHARACTER SET 'big5' NULL DEFAULT NULL,
  `city` VARCHAR(15) NOT NULL,
  `postcode` VARCHAR(10) NOT NULL,
  `address_line1` VARCHAR(20) NOT NULL,
  `valued_customer` VARCHAR(3) NOT NULL,
  `email` VARCHAR(35) NULL,
  `account_holer_idaccount_holer` INT NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `customer_id_UNIQUE` (`customer_id` ASC),
  INDEX `fk_customer_account_holer1_idx` (`account_holer_idaccount_holer` ASC),
  CONSTRAINT `fk_customer_account_holer1`
    FOREIGN KEY (`account_holer_idaccount_holer`)
    REFERENCES `bapersdb`.`account_holer` (`idaccount_holer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`discount` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`discount` (
  `idDiscount` INT(11) NOT NULL,
  `discount_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDiscount`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`fixed_discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`fixed_discount` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`fixed_discount` (
  `discount_rate` FLOAT NOT NULL,
  `Discount_idDiscount` INT(11) NOT NULL,
  PRIMARY KEY (`Discount_idDiscount`),
  CONSTRAINT `fk_fixed_discount_Discount1`
    FOREIGN KEY (`Discount_idDiscount`)
    REFERENCES `bapersdb`.`discount` (`idDiscount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`flexible_band`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`flexible_band` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`flexible_band` (
  `band_id` INT(11) NOT NULL AUTO_INCREMENT,
  `upper_Limit` DOUBLE NOT NULL,
  `lower_Limit` DOUBLE NOT NULL,
  `discount_Percentage` DOUBLE NOT NULL,
  `discount_idDiscount` INT(11) NOT NULL,
  PRIMARY KEY (`band_id`, `discount_idDiscount`),
  INDEX `fk_flexible_band_discount1_idx` (`discount_idDiscount` ASC),
  CONSTRAINT `fk_flexible_band_discount1`
    FOREIGN KEY (`discount_idDiscount`)
    REFERENCES `bapersdb`.`discount` (`idDiscount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`payment` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`payment` (
  `idPayment` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` FLOAT NOT NULL,
  `payment_type` VARCHAR(4) NULL DEFAULT NULL,
  `card_number` VARCHAR(45) NULL DEFAULT NULL,
  `expiry_date` DATE NULL DEFAULT NULL,
  `card_type` VARCHAR(10) NULL DEFAULT NULL,
  `invoice_sent` TINYINT(4) NULL DEFAULT NULL,
  `customer_customer_id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idPayment`, `customer_customer_id`),
  INDEX `fk_payment_customer1_idx` (`customer_customer_id` ASC),
  CONSTRAINT `fk_payment_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `bapersdb`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`job` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`job` (
  `Job_number` VARCHAR(10) NOT NULL,
  `deadline` DATETIME NOT NULL,
  `payment_state` VARCHAR(15) NULL DEFAULT NULL,
  `special_instructions` VARCHAR(250) NULL DEFAULT NULL,
  `late` TINYINT(1) NOT NULL,
  `completion_date` DATE NULL DEFAULT NULL,
  `Customer_customer_id` VARCHAR(15) NOT NULL,
  `total_cost` FLOAT NOT NULL,
  `payment_idPayment` INT(11) NULL DEFAULT NULL,
  `priority` INT(11) NULL DEFAULT NULL,
  `new` TINYINT NULL,
  `rushed` TINYINT NULL,
  `current_shelf` VARCHAR(45) NULL,
  PRIMARY KEY (`Job_number`, `Customer_customer_id`),
  UNIQUE INDEX `Job_number_UNIQUE` (`Job_number` ASC),
  INDEX `fk_Job_Customer1_idx` (`Customer_customer_id` ASC),
  INDEX `fk_job_payment1_idx` (`payment_idPayment` ASC),
  CONSTRAINT `fk_Job_Customer1`
    FOREIGN KEY (`Customer_customer_id`)
    REFERENCES `bapersdb`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_payment1`
    FOREIGN KEY (`payment_idPayment`)
    REFERENCES `bapersdb`.`payment` (`idPayment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`task` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`task` (
  `task_id` INT(11) NOT NULL AUTO_INCREMENT,
  `task_Description` VARCHAR(45) NOT NULL,
  `location` VARCHAR(25) NOT NULL,
  `shelfSlot` VARCHAR(25) NOT NULL,
  `price` FLOAT NOT NULL,
  `duration` INT(11) NOT NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`user_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`user_account` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`user_account` (
  `employee_id` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(15) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`job_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`job_task` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`job_task` (
  `Job_TaskID` INT(11) NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NULL DEFAULT NULL,
  `end_Time` DATETIME NULL DEFAULT NULL,
  `state` VARCHAR(15) NOT NULL,
  `time_taken` INT(20) NULL DEFAULT NULL,
  `shelf` VARCHAR(7) NULL DEFAULT NULL,
  `shift_type` VARCHAR(8) NULL DEFAULT NULL,
  `Task_task_id` INT(11) NOT NULL,
  `Job_Job_number` VARCHAR(10) NOT NULL,
  `Job_Customer_customer_id` VARCHAR(15) NOT NULL,
  `user_account_employee_id` VARCHAR(9) NULL DEFAULT NULL,
  `duration` INT NULL,
  PRIMARY KEY (`Job_TaskID`, `Task_task_id`, `Job_Job_number`, `Job_Customer_customer_id`),
  INDEX `fk_job_Task_Task1_idx` (`Task_task_id` ASC),
  INDEX `fk_job_Task_Job1_idx` (`Job_Job_number` ASC, `Job_Customer_customer_id` ASC),
  INDEX `fk_job_task_user_account1_idx` (`user_account_employee_id` ASC),
  CONSTRAINT `fk_job_Task_Job1`
    FOREIGN KEY (`Job_Job_number` , `Job_Customer_customer_id`)
    REFERENCES `bapersdb`.`job` (`Job_number` , `Customer_customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_Task_Task1`
    FOREIGN KEY (`Task_task_id`)
    REFERENCES `bapersdb`.`task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_task_user_account1`
    FOREIGN KEY (`user_account_employee_id`)
    REFERENCES `bapersdb`.`user_account` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`late_alert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`late_alert` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`late_alert` (
  `idLate_Alert` INT(11) NOT NULL AUTO_INCREMENT,
  `Aknowledged` TINYINT(1) NULL DEFAULT NULL,
  `job_Job_number` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idLate_Alert`),
  INDEX `fk_late_alert_job1_idx` (`job_Job_number` ASC),
  CONSTRAINT `fk_late_alert_job1`
    FOREIGN KEY (`job_Job_number`)
    REFERENCES `bapersdb`.`job` (`Job_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`payment_alert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`payment_alert` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`payment_alert` (
  `idAlert` INT(11) NOT NULL AUTO_INCREMENT,
  `aknowledged` TINYINT(1) NOT NULL DEFAULT '1',
  `alert_type` VARCHAR(45) NULL,
  `next_check` VARCHAR(45) NULL,
  `job_Job_number` VARCHAR(10) NOT NULL,
  `job_Customer_customer_id` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idAlert`),
  INDEX `fk_payment_alert_job1_idx` (`job_Job_number` ASC, `job_Customer_customer_id` ASC),
  CONSTRAINT `fk_payment_alert_job1`
    FOREIGN KEY (`job_Job_number` , `job_Customer_customer_id`)
    REFERENCES `bapersdb`.`job` (`Job_number` , `Customer_customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`valued_customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`valued_customer` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`valued_customer` (
  `customer_customer_id` VARCHAR(15) NOT NULL,
  `discount_idDiscount` INT(11) NULL,
  PRIMARY KEY (`customer_customer_id`),
  INDEX `fk_valued_customer_customer1_idx` (`customer_customer_id` ASC),
  INDEX `fk_valued_customer_discount1_idx` (`discount_idDiscount` ASC),
  CONSTRAINT `fk_valued_customer_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `bapersdb`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valued_customer_discount1`
    FOREIGN KEY (`discount_idDiscount`)
    REFERENCES `bapersdb`.`discount` (`idDiscount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`variable_discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`variable_discount` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`variable_discount` (
  `discount_rate` FLOAT NULL DEFAULT NULL,
  `Task_task_id` INT(11) NOT NULL,
  `Discount_idDiscount` INT(11) NOT NULL,
  PRIMARY KEY (`Task_task_id`, `Discount_idDiscount`),
  INDEX `fk_Variable_Discount_Task1_idx` (`Task_task_id` ASC),
  INDEX `fk_variable_discount_Discount1_idx` (`Discount_idDiscount` ASC),
  CONSTRAINT `fk_Variable_Discount_Task1`
    FOREIGN KEY (`Task_task_id`)
    REFERENCES `bapersdb`.`task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_variable_discount_Discount1`
    FOREIGN KEY (`Discount_idDiscount`)
    REFERENCES `bapersdb`.`discount` (`idDiscount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bapersdb`.`BackupData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bapersdb`.`BackupData` ;

CREATE TABLE IF NOT EXISTS `bapersdb`.`BackupData` (
  `idBackupData` INT NOT NULL,
  `tyoe` VARCHAR(45) NULL,
  PRIMARY KEY (`idBackupData`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
