/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//package this class belongs to
package bapers; 

//necessary imports for method calling functionallity
import Control.Controller;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luke1
 * Name of GUI frame class and local variables for storing information needed to display
 * 
 */
public class AddDicountPlan extends javax.swing.JFrame {
    LinkedList<Float> upperList;
    LinkedList<Float> lowerList;
    LinkedList<Float> ratesLinkedList;
    DefaultListModel ratesList;
    DefaultTableModel availableModel;
    DefaultTableModel addedModel;
    LinkedList<Integer> tasks;
    LinkedList <Float> varRates;
    
    //private static String custId;

    /**
     * Creates new form AddDicountPlan (Constructor) takes in no parameters
     * 
     */
    public AddDicountPlan() {
        initComponents(); //GUI method to diplay
        //lists in the gui
        upperList = new LinkedList(); 
        lowerList = new LinkedList();
        ratesLinkedList = new LinkedList();
        ratesList = (DefaultListModel) discBandsList.getModel();
        availableModel = (DefaultTableModel) availableTable.getModel();
        addedModel = (DefaultTableModel) addedTable.getModel();
        tasks = new LinkedList();
        varRates = new LinkedList();
        getTasks(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        discountPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fixedPercentageTxt = new javax.swing.JTextField();
        addFixedDiscountBtn = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        createBandBtn = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        upperBoundTxt = new javax.swing.JTextField();
        lowerBoundTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        discBandsList = new javax.swing.JList<>();
        removeBandBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FlexiRateTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        flexibleRateTxt = new javax.swing.JTextField();
        addFlexibleDiscountBtn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addedTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        availableTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        taskTxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        discIdTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("Discount Percentage: ");

        addFixedDiscountBtn.setText("Add Discount Fixed");
        addFixedDiscountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFixedDiscountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fixedPercentageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFixedDiscountBtn)
                .addGap(0, 271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fixedPercentageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFixedDiscountBtn))
                .addContainerGap(404, Short.MAX_VALUE))
        );

        discountPanel.addTab("Fixed Discount", jPanel1);

        createBandBtn.setText("Create Band");
        createBandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBandBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Lower bound: ");

        jLabel12.setText("Upper Band:");

        discBandsList.setModel(new DefaultListModel());
        discBandsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                discBandsListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(discBandsList);

        removeBandBtn.setText("Clear");
        removeBandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBandBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText("Bands: ");

        jLabel5.setText("Discount Rate (%):");

        jButton1.setText("Add Discount Variable");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(createBandBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeBandBtn))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FlexiRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upperBoundTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lowerBoundTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBandBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lowerBoundTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(createBandBtn)
                    .addComponent(upperBoundTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FlexiRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        discountPanel.addTab("Flexible Discount", jPanel3);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel10.setText("Tasks:");

        flexibleRateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flexibleRateTxtActionPerformed(evt);
            }
        });

        addFlexibleDiscountBtn.setText("Add Discount Flexible");
        addFlexibleDiscountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlexibleDiscountBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Discount Rate: ");

        addedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Task ID", "Task Desc", "Discount Rate (%)"
            }
        ));
        jScrollPane1.setViewportView(addedTable);

        availableTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Task ID", "Task Description"
            }
        ));
        jScrollPane4.setViewportView(availableTable);

        jLabel6.setText("Task ID: ");

        jButton2.setText("Add Task");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove Task");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addFlexibleDiscountBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flexibleRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taskTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(flexibleRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(taskTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFlexibleDiscountBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        discountPanel.addTab("Variable Discount", jPanel2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Add Discount Policy");

        exitBtn.setText("Close");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Discount ID: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(discIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(discountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(discIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addFixedDiscountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFixedDiscountBtnActionPerformed
        if (fixedPercentageTxt.getText().equals("") || discIdTxt.getText().equals("")){ //no empty values can be passed (doesn't make sense in scenario) and we generate a warnign message
            JOptionPane.showMessageDialog(null, "Enter Discount ID and Discount Rate",  "Add Discount", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                Controller.addFixedDiscount(Integer.parseInt(discIdTxt.getText()),Float.parseFloat(fixedPercentageTxt.getText())); //calls add discount method from controller class with values inputed in gui
            }catch(NumberFormatException ex){ //catching any wrong format issues like usage of Strings where Integers are needed
                JOptionPane.showMessageDialog(null, "Discount Rate and Discount ID must be numbers",  "Add Discount", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_addFixedDiscountBtnActionPerformed
    
    //close this gui frame and go back to main menu
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose(); //close this current frame
        Controller.openMainMenu(); //open main menu from controller class
        
    }//GEN-LAST:event_exitBtnActionPerformed

    //method for setting band in the discount
    private void createBandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBandBtnActionPerformed
        if (upperBoundTxt.getText().equals("") || lowerBoundTxt.getText().equals("") || FlexiRateTxt.getText().equals("")){
             JOptionPane.showMessageDialog(null, "Enter Values!",  "Add Discount", JOptionPane.WARNING_MESSAGE); //empty values in gui message 
        }else {
            try{
                float upper = Float.parseFloat(upperBoundTxt.getText());
                float lower = Float.parseFloat(lowerBoundTxt.getText());
                float rate = Float.parseFloat(FlexiRateTxt.getText());
                
                if (upper < lower && upper != 0 ){
                    JOptionPane.showMessageDialog(null, "Invalid Band",  "Add Discount", JOptionPane.WARNING_MESSAGE);
                }else{
                    upperList.add(upper);
                    lowerList.add(lower);
                    ratesLinkedList.add(rate);
                    ratesList.addElement(lower + " " + "-" + " " + upper + " " + "Rate: " + rate);
                }
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Upper, Lower and Discount Rate Must be numbres",  "Add Discount", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_createBandBtnActionPerformed

    private void addFlexibleDiscountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlexibleDiscountBtnActionPerformed
        if(tasks.isEmpty()){
            JOptionPane.showMessageDialog(null, "Add Tasks First!",  "Add Discount", JOptionPane.WARNING_MESSAGE); //can't add discount without tasks and shows appropriate warning message
        }else if(discIdTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Enter Discount ID!",  "Add Discount", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                Controller.addFlexidisc(tasks, varRates, Integer.parseInt(discIdTxt.getText()));
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Discount ID Must Be A Number",  "Add Discount", JOptionPane.WARNING_MESSAGE);
            }
        } 
    }//GEN-LAST:event_addFlexibleDiscountBtnActionPerformed

    private void flexibleRateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flexibleRateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flexibleRateTxtActionPerformed

    private void removeBandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBandBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeBandBtnActionPerformed
    //click to select band
    private void discBandsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discBandsListMouseClicked
        JList BandsList = (JList)evt.getSource();
        if (evt.getClickCount() == 2 && !upperList.isEmpty()) {
            int index = BandsList.locationToIndex(evt.getPoint());
            ratesList.removeElementAt(index);
            upperList.remove(index);
            lowerList.remove(index);
            ratesLinkedList.remove(index);
        }        
    }//GEN-LAST:event_discBandsListMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ( discIdTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Enter Discount ID ",  "Set Discount", JOptionPane.WARNING_MESSAGE);
        }else if(ratesList.isEmpty()){
            JOptionPane.showMessageDialog(null, "Add discount bands to variable discount",  "Add Discount", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                Controller.addVariableDiscount(upperList, lowerList, ratesLinkedList, Integer.parseInt(discIdTxt.getText()));
                ratesList.clear();
                upperList.clear();
                lowerList.clear();
                ratesLinkedList.clear();
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Discount Rate and Discount ID must be numbers",  "Add Discount", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (flexibleRateTxt.getText().equals("") || taskTxt.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Enter Discount rate and Task ID",  "Add Discount", JOptionPane.WARNING_MESSAGE);
        }else{
            try{
                boolean found = Controller.getTaskById(Integer.parseInt(taskTxt.getText()));
                float rate = Float.parseFloat(flexibleRateTxt.getText());
                boolean added = false;
                if(found == true){
                    for(int i = 0; i < addedModel.getRowCount(); i++){
                        if (addedModel.getValueAt(i, 0).toString().equals(taskTxt.getText())){
                            added = true;
                            JOptionPane.showMessageDialog(null, "Task Already Added To Discount!",  "Add Discount", JOptionPane.WARNING_MESSAGE);
                        }
                    }
                    if (added == false ){
                        String description = "";
                        for(int i = 0; i < availableModel.getRowCount(); i++){
                            if(taskTxt.getText().equals(availableModel.getValueAt(i, 0).toString())){
                                description = availableModel.getValueAt(i, 0).toString();
                            }
                        }
                        addedModel.addRow(new Object [] {taskTxt.getText(), description,flexibleRateTxt.getText()});
                        tasks.add(Integer.parseInt(taskTxt.getText()));
                        varRates.add(rate);
                    }
                }
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(null, "Discount Rate and Task ID must be numbers",  "Add Discount", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if (taskTxt.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Enter Discount rate and Task ID",  "Set Discount", JOptionPane.WARNING_MESSAGE);
        }else{
             try{
                 boolean added = false;
                 int taskID = Integer.parseInt(taskTxt.getText());
                 for(int i = 0; i < addedModel.getRowCount(); i++){
                        if (addedModel.getValueAt(i, 0).toString().equals(taskTxt.getText())){
                            added = true;
                            addedModel.removeRow(i);
                            for(int p = 0; p < tasks.size(); p++){
                                if(tasks.get(p) == taskID){
                                    tasks.remove(p);
                                    varRates.remove(p);
                                }
                            }
                            
                        }
                    }
                 if(added == true){
                     JOptionPane.showMessageDialog(null, "Task Removed",  "Add Discount", JOptionPane.WARNING_MESSAGE);
                 }else{
                     JOptionPane.showMessageDialog(null, "Task Not Found",  "Add Discount", JOptionPane.WARNING_MESSAGE);
                 }
             }catch(NumberFormatException ex){
                 JOptionPane.showMessageDialog(null, "Task ID Must Be  Number",  "Add Discount", JOptionPane.WARNING_MESSAGE);
             }
         }
    }//GEN-LAST:event_jButton3ActionPerformed
    //show tasks for applying discount
    private void getTasks(){
        availableModel.setRowCount(0);
        addedModel.setRowCount(0);
        ResultSet available = Controller.getAllTaskItems();
        if(available != null){
            try{
                while(available.next()){
                    String taskID = available.getString("task_id");
                    String description = available.getString("task_description");
                    availableModel.addRow(new Object [] {taskID, description});
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error Displaying Taks: " + ex.getMessage() ,  "Add Discount", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDicountPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDicountPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDicountPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDicountPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDicountPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FlexiRateTxt;
    private javax.swing.JToggleButton addFixedDiscountBtn;
    private javax.swing.JButton addFlexibleDiscountBtn;
    private javax.swing.JTable addedTable;
    private javax.swing.JTable availableTable;
    private javax.swing.JToggleButton createBandBtn;
    private javax.swing.JList<String> discBandsList;
    private javax.swing.JTextField discIdTxt;
    private javax.swing.JTabbedPane discountPanel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField fixedPercentageTxt;
    private javax.swing.JTextField flexibleRateTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField lowerBoundTxt;
    private javax.swing.JButton removeBandBtn;
    private javax.swing.JTextField taskTxt;
    private javax.swing.JTextField upperBoundTxt;
    // End of variables declaration//GEN-END:variables
    public void close(){
            WindowEvent winCloseEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winCloseEvent);
        }
}
