/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bapers;

import Control.Controller;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luke1
 */
public class CompletePayment extends javax.swing.JFrame {
    SelectJob sj;
    static String custID;
    LinkedList<String> addedJobs = new LinkedList<String>();
    DefaultTableModel addedModel = new DefaultTableModel();
    DefaultTableModel availModel = new DefaultTableModel();
    float total;
    /**
     * @param custID
     * Creates new form CompletePayment
     */
    public CompletePayment(String custID) {
        initComponents(); //start all gui related functions
        addedModel = (DefaultTableModel) addedTable.getModel();
        addedModel.setRowCount(0);
        availModel = (DefaultTableModel) availTable.getModel();
        availModel.setRowCount(0);
        this.custID = custID;
        addAvailJobs();
        
        total = 0;
        //sj = new SelectJob(this.custID, "custPaym");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cashPaymentBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        expiraryDate1Txt = new javax.swing.JTextField();
        typeTxt = new javax.swing.JTextField();
        cardNumberTxt = new javax.swing.JTextField();
        cardPaymentBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        addedTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jobNum = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        totalOut = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        availTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        expiraryDate2Txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        expiraryDate3Txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Complete Payment");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Cash Payment");

        jLabel3.setText("Amount: £");

        cashPaymentBtn.setText("Complete Cash Payment");
        cashPaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashPaymentBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Card Payment");

        jLabel5.setText("Expiry Date:");

        jLabel7.setText("Type:");

        jLabel8.setText("Card Number:");

        expiraryDate1Txt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                expiraryDate1TxtCaretUpdate(evt);
            }
        });
        expiraryDate1Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expiraryDate1TxtKeyTyped(evt);
            }
        });

        cardNumberTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberTxtActionPerformed(evt);
            }
        });

        cardPaymentBtn.setText("Complete Card Payment");
        cardPaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardPaymentBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Close");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        addedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Job Number", "Total Cost"
            }
        ));
        jScrollPane2.setViewportView(addedTable);

        jButton1.setText("Add Job");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove Job");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Job Number:");

        totalOut.setText("-");

        jButton3.setText("Add All Late Jobs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        availTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Job Number", "Total Cost"
            }
        ));
        jScrollPane3.setViewportView(availTable);

        jLabel11.setText("/");

        expiraryDate2Txt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                expiraryDate2TxtCaretUpdate(evt);
            }
        });
        expiraryDate2Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expiraryDate2TxtKeyTyped(evt);
            }
        });

        jLabel12.setText("/");

        expiraryDate3Txt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                expiraryDate3TxtCaretUpdate(evt);
            }
        });
        expiraryDate3Txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                expiraryDate3TxtKeyTyped(evt);
            }
        });

        jLabel13.setText("Added Jobs:");

        jLabel14.setText("Available Jobs:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cardPaymentBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalOut))
                            .addComponent(cancelBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cardNumberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(typeTxt))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cashPaymentBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jobNum, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(25, 25, 25)
                                        .addComponent(expiraryDate1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(expiraryDate2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(expiraryDate3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cashPaymentBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(expiraryDate1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(expiraryDate2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(expiraryDate3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(typeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cardNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardPaymentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jobNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cashPaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashPaymentBtnActionPerformed
        if(addedJobs.isEmpty()){
            System.out.println("Add Jobs First"); //warns to pay for jobs that exist 
        }else{
        
        
        
        boolean result = Controller.payForJobsCash(custID, total, addedJobs);
        if (result == true){
            JOptionPane.showMessageDialog(null, "Payment Complete",  "Cash Payment", JOptionPane.INFORMATION_MESSAGE);
            Controller.suspendedPayment(custID);
            for(int i = 0; i < addedJobs.size(); i++){
                Controller.removePaymentAlert(addedJobs.get(i)); //pay for remaining jobs
            }
            this.dispose(); //close this
            Controller.openMainMenu(); //return to main menu
        }else{
            JOptionPane.showMessageDialog(null, "Error Completing Payment",  "Cash Payment", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_cashPaymentBtnActionPerformed

    private void cardPaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardPaymentBtnActionPerformed
        if(expiraryDate1Txt.getText().equals("") || expiraryDate2Txt.getText().equals("") || expiraryDate3Txt.getText().equals("")
                 || typeTxt.getText().equals("") || cardNumberTxt.getText().equals("") || addedJobs.isEmpty()){
            //no empty fields
            JOptionPane.showMessageDialog(null, "Empty Values!",  "Card Payment", JOptionPane.WARNING_MESSAGE);
        }else{
        
        
        String cardNum = cardNumberTxt.getText();
        String expDate = expiraryDate3Txt.getText() + "-" + expiraryDate2Txt.getText() + "-" + expiraryDate1Txt.getText();
        String cardType = typeTxt.getText();
        boolean result = Controller.payForJobsCard(custID, total, cardNum, expDate, cardType, addedJobs);
        if (result == true){
            JOptionPane.showMessageDialog(null, "Payment Complete",  "Card Payment", JOptionPane.INFORMATION_MESSAGE);
            Controller.suspendedPayment(custID);
            for(int i = 0; i < addedJobs.size(); i++){
                Controller.removePaymentAlert(addedJobs.get(i));
            }
            this.dispose();
            Controller.openMainMenu();
        }else{
            JOptionPane.showMessageDialog(null, "Error Completing Payment",  "Card Payment", JOptionPane.WARNING_MESSAGE);
        }
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_cardPaymentBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
this.dispose(); //close this gui frame
Controller.openMainMenu(); //return to main menu
// TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void cardNumberTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberTxtActionPerformed
        this.dispose(); //close this gui frame
Controller.openMainMenu(); //return to main menu
    }//GEN-LAST:event_cardNumberTxtActionPerformed
    
    //add job
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //sj.setVisible(true);       
    String number = jobNum.getText();
    int jobInt = 0;
    try{
            jobInt = Integer.parseInt(number);
    }catch (NumberFormatException ex){
        System.out.println("Invalid Job Number");
    }
        
    if(number.equals("")){
        System.out.println("EnterJobNumber");
    }else {
        getJobData(jobInt);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    //add all late jobs
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ResultSet rs = Controller.getlLAteJobs(custID);
        try{
            if (!rs.next()){
                System.out.println("No Late Jobs Found");
            }else {
                while(rs.next()){
                    getJobData(rs.getInt("Job_number"));
                }
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    //remove job
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String num = jobNum.getText();
        for (int i = 0; i < addedJobs.size(); i++){
            if (addedJobs.get(i).equals(num)){
                addedJobs.remove(i);
                for(int p = 0; i < addedModel.getRowCount(); p++){
                    if (addedModel.getValueAt(p, 0).toString().equals(jobNum)){
                        addedModel.removeRow(p);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    //card details expiry date text boxes
    private void expiraryDate1TxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiraryDate1TxtKeyTyped
       
    boolean max = expiraryDate1Txt.getText().length() > 1;
    if ( max ){
        evt.consume();
    }        

    }//GEN-LAST:event_expiraryDate1TxtKeyTyped

    private void expiraryDate1TxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_expiraryDate1TxtCaretUpdate
                                         

    String text = expiraryDate1Txt.getText();
    if(text != null) {
        if(!text.matches("[0-9]*")) {
            expiraryDate1Txt.setText("");                
        }
    }


    }//GEN-LAST:event_expiraryDate1TxtCaretUpdate

    private void expiraryDate2TxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiraryDate2TxtKeyTyped
        boolean max = expiraryDate2Txt.getText().length() > 1;
    if ( max ){
        evt.consume();
    }   
    }//GEN-LAST:event_expiraryDate2TxtKeyTyped

    private void expiraryDate2TxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_expiraryDate2TxtCaretUpdate
        String text = expiraryDate2Txt.getText();
    if(text != null) {
        if(!text.matches("[0-9]*")) {
            expiraryDate2Txt.setText(" ");                
        }
    }
    }//GEN-LAST:event_expiraryDate2TxtCaretUpdate

    private void expiraryDate3TxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_expiraryDate3TxtCaretUpdate
        String text = expiraryDate3Txt.getText();
    if(text != null) {
        if(!text.matches("[0-9]*")) {
            expiraryDate3Txt.setText(" ");                
        }
    }
    }//GEN-LAST:event_expiraryDate3TxtCaretUpdate

    private void expiraryDate3TxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expiraryDate3TxtKeyTyped
        boolean max = expiraryDate3Txt.getText().length() > 3;
    if ( max ){
        evt.consume();
    }   
    }//GEN-LAST:event_expiraryDate3TxtKeyTyped

    public void getJobData(int jobNum){
        boolean alreadyAdded = false;
        boolean found = true;
        LinkedList<String> data = Controller.getJobPayment(jobNum);
        if (data == null){
            System.out.println("Job Not Found");
            found = false;
            
        }else{
            //check alrady added 
            
            for(int i = 0; i < addedJobs.size(); i++){
                if (addedJobs.get(i).equals(Integer.toString(jobNum))){
                    alreadyAdded = true;
                    System.out.println("Job Already Added");
                }
            }
            
        }
        if(found == true && alreadyAdded == false){
            addedModel.addRow(new Object [] {data.get(0), data.get(1)});
            addedJobs.add(data.get(0));
            total = total + Float.parseFloat(data.get(1));
            updateTotal();
        }
    }
    
    //update total price
    public void updateTotal(){
        totalOut.setText(Float.toString(total));
    }
    
    //in order to pay for jobs must get them
    public void addAvailJobs(){
        System.out.println("Payment cust ID = " + custID);
        ResultSet rs = Controller.getAvailPAyJobs(custID);
        try{
            //availModel.addRow(new Object [] {rs.getString("Job_number"), rs.getString("total_price")});
                while(rs.next()){
                    availModel.addRow(new Object [] {rs.getString("Job_number"), rs.getString("total_cost")});
                }
            
        }catch(SQLException ex){
                System.out.println(ex.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompletePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompletePayment(custID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable addedTable;
    private javax.swing.JTable availTable;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cardNumberTxt;
    private javax.swing.JButton cardPaymentBtn;
    private javax.swing.JButton cashPaymentBtn;
    private javax.swing.JTextField expiraryDate1Txt;
    private javax.swing.JTextField expiraryDate2Txt;
    private javax.swing.JTextField expiraryDate3Txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jobNum;
    private javax.swing.JLabel totalOut;
    private javax.swing.JTextField typeTxt;
    // End of variables declaration//GEN-END:variables
}
