/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bapers;
import Entity.UserAccount;
import Control.*;
/**
 *
 * @author luke1
 */
public class MainMenu extends javax.swing.JFrame {
     
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        UserAccount ua = Controller.getUa();
        roleLabel.setText(ua.getRole());
        idLabel.setText(ua.getEmployee_id());
        if (ua.getRole() .equals("Receptionist") ){
            updatejobBtn.setEnabled(false);
            customerReportBtn.setEnabled(false);
            employeeReportButton.setEnabled(false);
            SummaryReportBtn.setEnabled(false);
            completePaymentBtn.setEnabled(false);
            mngLateBtn.setEnabled(false);
            editDiscBtn.setEnabled(false);
            removeDiscountBtn.setEnabled(false);
            createUserBtn.setEnabled(false);
            backupBtn.setEnabled(false);
            restoreBtn.setEnabled(false);
            add.setEnabled(false);
            
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            
        }else if(ua.getRole().equals("Shift Manager")){
            //updatejobBtn.setEnabled(false);
            
           // completePaymentBtn.setEnabled(false);
            mngLateBtn.setEnabled(false);
            editDiscBtn.setEnabled(false);
            removeDiscountBtn.setEnabled(false);
           // createUserBtn.setEnabled(false);
            backupBtn.setEnabled(false);
            restoreBtn.setEnabled(false);
            add.setEnabled(false);
            jButton4.setEnabled(false);
            createUserBtn.setEnabled(false);
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            completePaymentBtn.setEnabled(false);
            
        } else if (ua.getRole().equals("Technician")){
             //updatejobBtn.setEnabled(false);
            customerReportBtn.setEnabled(false);
            employeeReportButton.setEnabled(false);
            SummaryReportBtn.setEnabled(false);
            completePaymentBtn.setEnabled(false);
            mngLateBtn.setEnabled(false);
            editDiscBtn.setEnabled(false);
            removeDiscountBtn.setEnabled(false);
            createUserBtn.setEnabled(false);
            backupBtn.setEnabled(false);
            restoreBtn.setEnabled(false);
            add.setEnabled(false);
            customerAccountBtn.setEnabled(false);
            newJobBtn.setEnabled(false);
            jButton5.setEnabled(false);
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
        }
        //JOptionPane.showMessageDialog(null, "The system has detected late payments! ",  "Late Payments Found", JOptionPane.OK_CANCEL_OPTION);
       //JOptionPane.showMessageDialog(null, "Job JC4542 Is Running Late! ",  "Late Job", JOptionPane.WARNING_MESSAGE);
       //JOptionPane.showMessageDialog(null, "Database Connection Failed!, Quiting Application",  "Failed Connection", JOptionPane.ERROR_MESSAGE);
        
//firstRemindersBtn.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        newJobBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        roleLabel = new javax.swing.JLabel();
        updatejobBtn = new javax.swing.JButton();
        completePaymentBtn = new javax.swing.JButton();
        backupBtn = new javax.swing.JButton();
        restoreBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        customerReportBtn = new javax.swing.JButton();
        employeeReportButton = new javax.swing.JButton();
        createUserBtn = new javax.swing.JButton();
        customerAccountBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editDiscBtn = new javax.swing.JButton();
        removeDiscountBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        SummaryReportBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        add = new javax.swing.JButton();
        mngLateBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        newJobBtn.setText("New Job");
        newJobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newJobBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Main Menu");

        idLabel.setText("ID");

        roleLabel.setText("Role");

        updatejobBtn.setText("View / Update Job");
        updatejobBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejobBtnActionPerformed(evt);
            }
        });

        completePaymentBtn.setText("Complete Payment");
        completePaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completePaymentBtnActionPerformed(evt);
            }
        });

        backupBtn.setText("Backup Database ");
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });

        restoreBtn.setText("Restore from Backup");
        restoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreBtnActionPerformed(evt);
            }
        });

        customerReportBtn.setText("Generate Customer Report ");
        customerReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerReportBtnActionPerformed(evt);
            }
        });

        employeeReportButton.setText("Generate Employee Report");
        employeeReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeReportButtonActionPerformed(evt);
            }
        });

        createUserBtn.setText("Create User Account");
        createUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserBtnActionPerformed(evt);
            }
        });

        customerAccountBtn.setText("Create Customer Account ");
        customerAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAccountBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("BAP-ADMIN");

        jLabel3.setText("BAP-CUST");

        editDiscBtn.setText("Set Discount");
        editDiscBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDiscBtnActionPerformed(evt);
            }
        });

        removeDiscountBtn.setText("Remove Discount");
        removeDiscountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDiscountBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("BAP-PAYM");

        jLabel5.setText("BAP-REPT");

        SummaryReportBtn.setText("Generate Summary Report");
        SummaryReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummaryReportBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("BAP-PROC");

        jLabel7.setText("BAP-ACCT");

        add.setText("Add / Edit Tasks");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        mngLateBtn.setText("Manage Late Payments");
        mngLateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngLateBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Upgrade Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Downgrade account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Manage User Accounts");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Edit Customer Account");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setText("Employee ID:");

        jLabel9.setText("Employee Role: ");

        jButton3.setText("Add Discount Plan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator4)
                        .addComponent(jSeparator2)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(createUserBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(backupBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restoreBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(add)
                            .addGap(4, 4, 4))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(completePaymentBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mngLateBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(editDiscBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(removeDiscountBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(customerReportBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(employeeReportButton)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SummaryReportBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(customerAccountBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(newJobBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5))
                        .addComponent(updatejobBtn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(logoutBtn)
                            .addGap(69, 69, 69)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idLabel)
                            .addGap(48, 48, 48)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(roleLabel))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerAccountBtn)
                    .addComponent(newJobBtn)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatejobBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerReportBtn)
                    .addComponent(employeeReportButton)
                    .addComponent(SummaryReportBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completePaymentBtn)
                    .addComponent(mngLateBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editDiscBtn)
                    .addComponent(removeDiscountBtn)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(8, 8, 8)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createUserBtn)
                    .addComponent(backupBtn)
                    .addComponent(restoreBtn)
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idLabel)
                    .addComponent(jLabel9)
                    .addComponent(roleLabel)
                    .addComponent(logoutBtn))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
 * When the user pressed the logout button this frame is disposed of, and the 
 * login page is displayed
 * @param evt 
 */
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
this.dispose();
LoginDesign ld = new LoginDesign();
ld.setVisible(true);
Controller.setUa(null);
Controller.setLogedIn(false);// TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed
/**
 * Disposes of this form and opens the SelectJob form
 * @param evt 
 */
    private void updatejobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejobBtnActionPerformed
SelectJob sj = new SelectJob("-1", "update");
this.dispose();
sj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_updatejobBtnActionPerformed
/**
 * Disposes of this form and opens the SelectCustomer form
 * @param evt 
 */
    private void completePaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completePaymentBtnActionPerformed
        SelectCustomer cp = new SelectCustomer(3);
        cp.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_completePaymentBtnActionPerformed
/**
 * creates a new backups form and makes it visible
 * @param evt 
 */
    private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtnActionPerformed
SetUpBackups sb = new SetUpBackups(); 
sb.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backupBtnActionPerformed
/**
 * opens the form for customer reports
 * @param evt 
 */
    private void customerReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerReportBtnActionPerformed
        CustomerReport cr = new CustomerReport();
        cr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerReportBtnActionPerformed
/**
 * opens the form for employee reports
 * @param evt 
 */
    private void employeeReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeReportButtonActionPerformed
        IndividualReport id = new IndividualReport();
        id.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_employeeReportButtonActionPerformed
/**
 * Disposes of this form and opens the SelectCustomer form
 * @param evt 
 */
    private void newJobBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newJobBtnActionPerformed
        SelectCustomer nj = new SelectCustomer(2);
        nj.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_newJobBtnActionPerformed
/**
 * Disposes of this form and opens the CreateCustomer form
 * @param evt 
 */
    private void customerAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAccountBtnActionPerformed
         CreateCustomer cc = new CreateCustomer("create", "-1");
         cc.setVisible(true);
         this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_customerAccountBtnActionPerformed
/**
 * Disposes of this form and opens the CreateAccount form
 * @param evt 
 */
    private void createUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserBtnActionPerformed
this.dispose();
CreateAccount ca = new CreateAccount();
ca.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_createUserBtnActionPerformed

    private void restoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreBtnActionPerformed
        DBRestore dr = new DBRestore();
        
    }//GEN-LAST:event_restoreBtnActionPerformed
/**
 * opens the form for managing late payments
 * @param evt 
 */
    private void mngLateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngLateBtnActionPerformed
ManageLatePayments mp = new ManageLatePayments();
this.dispose();
mp.setVisible(true);
    }//GEN-LAST:event_mngLateBtnActionPerformed
/**
 * Disposes of this form and opens the AddTasks form
 * @param evt 
 */
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
this.dispose();
AddTasks et = new AddTasks();
et.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed
/**
 * Disposes of this form and opens the SelectCustomer form
 * @param evt 
 */
    private void editDiscBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDiscBtnActionPerformed
        this.dispose();
        SelectCustomer selectCust = new SelectCustomer(1);
        selectCust.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_editDiscBtnActionPerformed
/**
 * Disposes of this form and opens the SelectCustomer form
 * @param evt 
 */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
        SelectCustomer sc = new SelectCustomer(5);
        sc.setVisible(true);        
    }//GEN-LAST:event_jButton1ActionPerformed
/**
 * disposes of this form and opens the manage user accounts form
 * @param evt 
 */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ManageUserAccounts mu = new ManageUserAccounts();
        mu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed
/**
 * Disposes of this form and opens the SelectCustomer form
 * @param evt 
 */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
        SelectCustomer sc = new SelectCustomer(4);
        sc.setVisible(true);
        //SelectCustomer sc = new SelectCustomer(4);
        //sc.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed
/**
 * Disposes of this form and opens the SelectCustomer form
 * @param evt 
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        SelectCustomer sc = new SelectCustomer(6);
        sc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
/**
 * Disposes of this form and opens the SelectCustomer form
 * @param evt 
 */
    private void removeDiscountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDiscountBtnActionPerformed
        this.dispose();
        SelectCustomer sc = new SelectCustomer(7);
        sc.setVisible(true);
    }//GEN-LAST:event_removeDiscountBtnActionPerformed
/**
 * disposes of this form and opens the add discount plan form
 * @param evt 
 */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();
AddDicountPlan ad = new AddDicountPlan();
ad.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SummaryReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummaryReportBtnActionPerformed
        WorkSummaryReport ws = new WorkSummaryReport();
        ws.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SummaryReportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SummaryReportBtn;
    private javax.swing.JButton add;
    private javax.swing.JButton backupBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton completePaymentBtn;
    private javax.swing.JButton createUserBtn;
    private javax.swing.JButton customerAccountBtn;
    private javax.swing.JButton customerReportBtn;
    private javax.swing.JButton editDiscBtn;
    private javax.swing.JButton employeeReportButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton mngLateBtn;
    private javax.swing.JButton newJobBtn;
    private javax.swing.JButton removeDiscountBtn;
    private javax.swing.JButton restoreBtn;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JButton updatejobBtn;
    // End of variables declaration//GEN-END:variables
}
